---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQQ2CzS+daxC9zloGEf88iczAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMjMwNDM2MDBaFw0zNDEyMjEwNDM2
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAESgRKFJiI8aSYsvNPjoZJeETZbC8BqZhti+rhbaHMQ0fYGtAXE1wyxQUr
          pBfOFCsLnfL0UE1P8WOn0I/2/5ZZ5aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCAhn8zBtuWIT6tzpv0KBw5cWT0bmcg2g4VoWIh5t0qZZzAKBggqhkjOPQQD
          AgNIADBFAiEAio4J/pj76/kBKzuvHRtapc7KNwF/TIRywuFZtu5IKHECIAC7o6GF
          7QO7lMM3MccohHynCOMU2wiUM4Xv7Rv4D2Wb
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUDCCAfegAwIBAgIQc7BSbv6Mck+yGqgeAH3JfDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMjMwNDM2MDBaFw0zNDEyMjEwNDM2MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          awjRwon67mS6WtxmDnqb1F/wcmbhDs+vJwejQt1hJNpfAN44ynPNAtCMhwTzKtQV
          j39/DgW6jQxuYEaDUyjRQ6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDt
          wqlg6Nfohv4+dx4fB/cw8nvAzV1MIf57tY8jY4mEJjAKBggqhkjOPQQDAgNHADBE
          AiBYvuTN+jARF074UiJykGkU2NcAYoPeZ06iNBC+Hvnd5QIgUDDkZ35NoU8FblTo
          eqQBRvOTek2ajyPYKe0iQ4irL0Y=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
