---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRANud5uvmwXP2jxRX/ERnSdMwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTMxNDAwWhcNMzQxMjE4MTMx
          NDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABHd5VjT9/fZIpPixwEydV4EFhfDylU7UmKuctO6EmXa8yIw6Z3CGqAQL
          J7oephSwLc80/LLODhJshH+pnPaIFXCjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgFTtY9ZZkKnLxB6kNRE7HIKLAsDQvVwaiUid28nXCOAAwCgYIKoZIzj0E
          AwIDRwAwRAIgIGDhUKC1oFq9YA7j/LOrbstbhWAJxQ3GqD/+p5zdi3ECICNmE9mW
          1xmXrm2z5opgmhlUJgtSH+VfwF7+J07hSu5p
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAOYuI4igpCXU5IKn14bma/owCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTMxNDAwWhcNMzQxMjE4MTMxNDAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BBJ0mHEw8gtYJIrggHTKKt9gkJUwgen21IohvDoGeVyqwtTyZ+vQj0l7sffjqWth
          pPNDB7nEyObxprC5lPDnB0OjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          zlFrQ/YH/Ohwq1ckIQA6CSzUxKeg0rszZmHPE53VwCUwCgYIKoZIzj0EAwIDRwAw
          RAIgBTX9pQlt14cAjZno353nHbLAknTjcWkbYAfbDn31nZsCIBWgGvbdNIYZaZvt
          uQJq4X6w/PYHahFISI5i7f79ROWz
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
