---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRALqu+jJDAn2WJXJ1XoUobBwwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTAzNDAwWhcNMzQxMjE4MTAz
          NDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABBq38nMBTyfaETUVoF7ENXr0kfKO7x0oD6xRzVs2sznKbiAiLEZKftOM
          gtf5R0QznwhII7na4m/Jh7oJTWI0kvujbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgQQVUs10w6Ug62A8y3QQn/jkx+2joPqXdChf0177RXiIwCgYIKoZIzj0E
          AwIDSQAwRgIhAOfmikjEx/LzzxlGfKwQd+xHjxh32Af0Oxv0lsZp2rQTAiEAmLyS
          o1XhdSAXqoRurMCjunRwiDeR9cGK0iERBr+Hvfo=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQLkos39OnK48qXwHqUIph/jAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMjAxMDM0MDBaFw0zNDEyMTgxMDM0MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          fWTN8HClMH91tlwsne1xasw5thCwxWPfHWfaEm88hsFo791fqbTtzNsEkTLdJfaK
          ULuggZz1CPTFOihYH9x0iKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAv
          m/+XxZgPnGYN3VWgb89Juh8QYBDc51TlOZ4JNN9KojAKBggqhkjOPQQDAgNIADBF
          AiANiRPTedMrNIC+Y6ZAz6B7bptLilOaZRuaCV1+gmZzPAIhAKxPxu3Vmy+v2KFd
          rYGVYRBV14xK3eNXMCotuSah45/5
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
