---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRAMqSK9PQHEoQj8IEPZsaIncwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjEwMDI1NzAwWhcNMzQxMjA4MDI1
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABJhRj006vT7ynkkIy8RArytOjVF/zEVA+fB0QNxe6niMhJyh8LUU5/ba
          Ev3UPB3d7QE/PbCpT/yVxl60I8l6Lr+jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgXNZWzZ3qX+CuJfHyPLo4hxJ+87XYxS3epyKfm8hFJQMwCgYIKoZIzj0E
          AwIDRwAwRAIgU3bapLIbsP75e7T7lXAjlhbOi7pRpznZIY3eZ/WG7bwCIDE+edd2
          7sGgNPL5tphAM/75vNsNVm6FuM7ag/zJsnOg
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUDCCAfegAwIBAgIQdt73QGr4tbcYGs6210TyxzAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMTAwMjU3MDBaFw0zNDEyMDgwMjU3MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          urug9ltrieCQ9Kcfa2tDnOvexqzlk08gYmzlDoFsGlqfktk5xxsMmsivUSl0ra9R
          A1I68WRzP/7A19e7tgW1a6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCB8
          AI6GmMyqBQ6X5XgAqRHckiUsD29tLHRTTuEbVTdGoTAKBggqhkjOPQQDAgNHADBE
          AiBHz46XRLfNl6a2q/rGsCzpUGzJmLy72BXqpHeqBVNPSgIgdQimMZPSgV9bdNw+
          sUX1OtzKV9muUdpYMVhLEuZh+Ec=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
