---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRALG4NG0ywMgUM8N+HoVGANswCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjAyMTIzNjAwWhcNMzQxMTMwMTIz
          NjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABHCz/RiRYqUp01oHlWJShAuvfx8E7xNjSvdiDFITbiG6f/O4q415bLLf
          SjJhorirPw03VZtSGuNQyTGQrpuMykKjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgfhUzaFJfry57s5i94TefCBZ+QGuV8d6A+xSUOirmMt8wCgYIKoZIzj0E
          AwIDRwAwRAIgN84BdgxA9F0lIsS6gIZPVgFSe5NMGxnCk+IdQb/p0FkCIHYlGSj/
          mgP6HvUPY2u7zCDUbK5BOtI0q9te1zY5hfDs
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQL07A45QLDZQK4+C4jx9Z2jAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDIxMjM2MDBaFw0zNDExMzAxMjM2MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          8Spenni8rS12+tt9qrbv/0VMY+yBsZ7hhYHZtxMq+U45acRVw7h9E+9YXAej7qqO
          f/faPMoE4NFsEv0ghdEBBKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCo
          /CWHSTbp+Sii9bfsEzdhblinTL2SJ9cfxPiSdjWNHjAKBggqhkjOPQQDAgNIADBF
          AiBhQlfyfpt6xLsIvWPI1VN0fzcrewgJ32E4GKpuMEJfMwIhAMVJKyCc1A9ceEL0
          QG7EONxFKXd1Hw5w7OmNpM9vqlLX
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
