---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRAK++Ud8hKO6jVJ6GtOykGwswCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjE5MDgxMjAwWhcNMzQxMjE3MDgx
          MjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABO4u0fuMUVdZNHBol0OTiXfT6oEFjuHdg6njFTImdj8TGhOLSSpbW+AK
          q/89vdICyIaI7BOT1gFhpA8WUZbKicSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgJ+FwNJRQSedvnqOuD1lRpBnGPF8+LX3Lp9YyqI9WFm8wCgYIKoZIzj0E
          AwIDSQAwRgIhAJgL4geGeK6mBMbOHiuz3twddHAXhRVliOGh57p8a2FTAiEAlQXm
          lLtpODGEtptkSv4Ka5B9mmKH5LszWDn1stBACKw=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUDCCAfegAwIBAgIQdzMLoXeU2mzS/0KRtYVTFjAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMTkwODEyMDBaFw0zNDEyMTcwODEyMDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          LlLEs5m/0vGKDCJmR+TCVbFrPtHNUMm0UI4DarySCEge3v4yU+KZCeinzsOeR0BW
          XRuJSf8TYP8/8cSUqPg1zaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDB
          2/G6Xvpzq0y3P2RENtib2ZKj6uxxmtiA3VGoM3WWkzAKBggqhkjOPQQDAgNHADBE
          AiBlU9gCfE/CXaZWsrdq9Z8wTsfyQpCdwqcRrSTd9v1RRAIgMRjby4Lk4U1wvDRl
          Zhs9XmItRrNz+enJGemQmP9Qvas=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
