---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAPpnEMod9meJMIosqWpBx5AwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjAyMDM1ODAwWhcNMzQxMTMwMDM1
          ODAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABHdQvFHXMAM56FPQ7PCGfTfLYycE37s1Tq7Oz/9cbuwHRMZQlXh6MXBg
          d3rmNa5KOlsj9wb0OMDHA3Bp30OjByWjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgGUp1dq2WtbS6XCrTrHRmSL4zcz8Pz5VwP/jkRTlUuLcwCgYIKoZIzj0E
          AwIDSAAwRQIgLIG89iXnIBjeEv5inNzzxhuUu4snoJkVvH14ccweZIICIQCCwFQH
          jSQj4a0KU+lU64JomTGvGfuqQL0RurpishVQiA==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRAOV3+o4y5pTgQESHnDzOqbAwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjAyMDM1ODAwWhcNMzQxMTMwMDM1ODAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BKNLb/A1h9r66zZVbXnI9HPtXqbLOropTEGhNUDN3+ugIkUtXa/cGdAkeKvv2dT4
          lzwNl/74o+wmFwMfssnlvpOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          xbSaje+YUpZVv/Qj6ncU5ctNehZbinr/X533yz+gTpAwCgYIKoZIzj0EAwIDSQAw
          RgIhANeJVW/TLYtnWkm+ZESaAf9A19i3ei0Zt1dYBOpM7R4SAiEAup3/zeFQ2r7o
          dQ9JSZJOUD8psIvbUIfsVlGufaAyG1E=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
