---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRAMUhFA85SJKF9q5VINrhLMgwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjAxMDk1NzAwWhcNMzQxMTI5MDk1
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABJykI/fT69pXPC4T/YeAbCNggaYReTeesm6C2XL+TivCZh2WDPyePy+s
          uu3HHQhOpPeFpsNmUvPl1x+nTqA7hnOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQg/ZYs5oHlGXaHmO6kgkQVJ+TnWFWBjZpxP3kOJeYT3uowCgYIKoZIzj0E
          AwIDSQAwRgIhAJfVqcGAWP+av2uU64CvQDV4LzZ2uY0CzHh5hNR8KqGhAiEA/ZNQ
          qpvXQETrMPtIYM0T/bIe9LGGMgUkurT761ITbpY=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRAPFDpcn32hEILvZl5WsVfU0wCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjAxMDk1NzAwWhcNMzQxMTI5MDk1NzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BJ0S+RkxhIQ+3KuQFTIfuidzTMYaVGn3esMIZKSti7OEHdNHmDSmfmMTIZ8aAGrf
          GnC66Z7dXkuSx4vOXCPhAZOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          eBfGecke7XrE1D3v8vON3vmJH03nnyXS9kxMNzWqG1EwCgYIKoZIzj0EAwIDSQAw
          RgIhAMz1JwOvisK76GOkADiIRyE3jeTgupYCoFkQvHH6FgoUAiEAm5Yv4it2LpqZ
          S+pp0rPlZFCXQ+jgMEfCL3lapuOkxcw=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
