---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf2gAwIBAgIQT0s5iQ/1bcLQM51F2rON8jAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDYwMjAxMDBaFw0zNDEyMDQwMjAx
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEtKZJFOvU8RqpFMQi0/DwW5ionxUE4X9bC7fb6WhPpJK286WhUkNQosO3
          VDg/3hRTyXROgzX0tGjvABm7ud0P3KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCC5SlqP9jQGE7PevzkxUWGLMokXimdBb1ePWIlntSC5uTAKBggqhkjOPQQD
          AgNJADBGAiEAn4y3xNOSJQewDQsvwNLXCHsNeO3qVaq8CjX4ZChbllwCIQDz98eQ
          hkWybdNz2fEjccGeoV2OsBO878EEKeyAwo5ofA==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRAPgUpJu1kqNoicHjIRhOa0EwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjA2MDIwMTAwWhcNMzQxMjA0MDIwMTAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BGxt6WhbVJk/ds2rM+JUshonr7Jgy9r38JekLvbEF+VYdoFypkvOkIdh2pkUBh82
          YMyNLfjGMr82x3GEag+IvgajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          ZZJtXfQt8VS9W0x6nw2mOfi3xyioxOxOviP+7i/gVu4wCgYIKoZIzj0EAwIDSAAw
          RQIgcFd8CmZng6gemU/QSrxRiIPcS7tpX0lLBWdZQ/u2z7ICIQDTl1AxgY+CVKCx
          gSU8ZqHEMrAEGA4YoqKaXvaF/a3tpw==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
