---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQHhDrJczG8kWLjF4mw8qhezAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDYwNDQ5MDBaFw0zNDEyMDQwNDQ5
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAElnZoUxTuz9E++q/s3Kyn3sGCWJub8rjMYsEAMvmks+9ctemXmdp01Dy+
          6Geep98kMTWwHOWQjmUV7321TGxRWaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCA5JZAH0CZ3HQm6+Tf28aSshVkTAKWKCKMdASNIxaD6BzAKBggqhkjOPQQD
          AgNIADBFAiBgndwuRF9iFO6XWPiwHoIuwQeiQup1jJ9KV5JrP71s2gIhAMfp5R8e
          WcCtR7XI1utK8Y+2ZIEIUy/nGV9M3Z6dr+5h
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQG4sOYCfVtT+fB0Wx3HfjRDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDYwNDQ5MDBaFw0zNDEyMDQwNDQ5MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          m25tTvjrXDdSi1NZRSQcYHHEYAXTN8QNOM2a/iQflHW0IYCO0uILKpMFOeiFeJ6m
          /LxifMjJDhfHy/NbXYkEY6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDy
          q8B2mpHrUoGgO7BUOyxAtx/Ub3T0V/RZR4atIfkexTAKBggqhkjOPQQDAgNIADBF
          AiAIwJ4CPbZ/dCrxKjlPuWzY7pMCYj/TnNpsgBIe1lhE9AIhANj7wWQv1Agocwru
          EnT82gygVewkqBNdB0QhQaGryL1t
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
