---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQXEqnAiomn6yRahfaG+cWyjAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDcxMTQwMDBaFw0zNDEyMDUxMTQw
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEnINF4M9Q/w79M9bEnQb19a9Rwi7XXfo/XBqPNEfb5T1OG9emDGJ28pnk
          iYIOzoR1qXNSYWxtpmK7CM0gd1KgfqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCB6aDL1NNKuOyTldvw1u0idF4QogA/KO/5YrfrbYpvKeTAKBggqhkjOPQQD
          AgNIADBFAiEA9OzLDVBMeo1kc/VwqJ2cC6pm92JY8g34A6YCFSlXN5QCID0zNwc5
          3xVzAU0eQMveA4eWzDn1lINCJkPtTgAA7NQ7
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQTUB9p7JlyPJjDCFJO/hwvDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDcxMTQwMDBaFw0zNDEyMDUxMTQwMDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          sb5ygDqtPboQZiTzo6ulY66J+Fq/CSKHAR0xbNYamOPjLmoG5PMf2xTiju8s3doB
          Wr0fpmV5lcG1Y1lODKLfYaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBJ
          ASJPMraiU8tS4uIr4Qu4vqg7k20NHdf2NAr/h3d1KzAKBggqhkjOPQQDAgNIADBF
          AiAkcDj9NrPeRidSDeCdeArsZcIgUORy24zClKxJSX/YhgIhAIvFz2Tg/YMyb4Xg
          HVg8tnQVs63bGaaU+Qmv+brrBFaP
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
