---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf2gAwIBAgIQWrFNQwXqwNHhdoZ/XOGzYDAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDExMjIwOTI1MDBaFw0zNDExMjAwOTI1
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEOIp4/1q4VTVGCGCr9hiocqUOQJfYL5OxYGToTXh+5Fqz2nr+Ul7tLQZG
          u/S9b6DYEMycWrhzSINs/X7V7CIrmqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCAtzfM4mYQ6vrFUK5YtEqAKnDTX2xSCwdWh6+dBGY/uPTAKBggqhkjOPQQD
          AgNJADBGAiEA1nXHYVg68/W3NC79cXsbs+fNxV03DoqAScquHs5qNXACIQCno55P
          Bk/27P+7fks1B3QpKWvhexYAAiVf3+s7pc3JzA==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAKiCSjb+eGvol2nMqh0qIBcwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMTIyMDkyNTAwWhcNMzQxMTIwMDkyNTAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BBNOO2lCu0dS8URiCGT5Ujme+wVLrBnJgwbe0PZ5Ul8OuvnsCodVBjuA4qR0vn5Z
          I+TLh7edMqUk9Wq9F0u9+/SjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          sk/hAs2fZIYeWZ65UYSVrduPpj60qo+1om37aBKVXtswCgYIKoZIzj0EAwIDRwAw
          RAIgBWZvEhIjU8Xmf62abygvcdgwfM0VkDe1u5U+qukNWqUCIGApwQrVJ/piE00Y
          okeZb7o7+R4nilwlgFLenYCMIpw9
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
