---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRAPNVM21tEzw/SA7fFGzdVaowCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjA2MTIyNTAwWhcNMzQxMjA0MTIy
          NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABAkFifAo4kIa3S2kRxkHyNeYkXdgTg7hOFGC0z238cmcA9YPskP2/DKI
          0hIFn2dGUrBGJ4Kn80ce1hVZDlAUHamjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgTukSteNnG4qFtCsmm0fofivmHTwCcjqFPrbYKsiXilUwCgYIKoZIzj0E
          AwIDSQAwRgIhAJcRkBYtcPsgCdCTsZMy2w4KprQTS0SeEv8Wu71V17AdAiEAq8B6
          VzpYv8Ycwci26V59dhGnPTZbgMKDyOQAHBTomSU=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQef6me56Os305SfmZVU3qHDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDYxMjI1MDBaFw0zNDEyMDQxMjI1MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          XMwD6TwwDlZKr1qpS+C6AxLXyjg6lrV3esNzq6T864TSyExGS3qLpsEy4iRNJaSn
          Za6BLeCkzYpigokdQQCBKKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBp
          RdR0rHjKPR/mIFqGtSoLbt1w/CxZ3n/Y4YOrhZSCWDAKBggqhkjOPQQDAgNIADBF
          AiBUq6xMc+cIqBB2z6Icc/E3svy8RYiUH2woIpB4NnnE7wIhAIfn83csTeNm8HFU
          UR+Bc+r2pap69XtlXI7z+O6g7Cq7
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
