---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQetTXT5E40xwD6PnKr19FmTAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMTAxMTA3MDBaFw0zNDEyMDgxMTA3
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEFIQ7YCLECDO2PtgK6/VgCbmrNSBYW3KaAZNtuWFGPPCVBPQ2qRUX/lvK
          3HNL0TmqKAc1Yx8BGVP6T13xeScaT6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCC8kI2KBP/ae6M3tcZgB32bLjZ0b5sXGpjoSzW5ewTmADAKBggqhkjOPQQD
          AgNIADBFAiEA7QqB01CO3dQXHrKKJSLi8B/vvCWxlWF+Pz9QsFHl/j0CIBkSnvgl
          YMuYliaAkDGRbuX9/MFJbGOXVxtVQthSEfUb
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAKx6jUPQv/RsHB3IaXdP8TgwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjEwMTEwNzAwWhcNMzQxMjA4MTEwNzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BLW94g2KpldhoCx1FmYtUhrGZfDrURGPi/SxkfE/MFOOlmg8nd/Zky4bPjFVz15M
          6HcP/Z/aouuL1miQBpLPrzKjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          nV3pn7MI6R4JWibE6CHtiFLon5WWg4Aghjq6ucYuEX8wCgYIKoZIzj0EAwIDRwAw
          RAIgX5/WNpGZh82BWCz71hbAHP781TKX0E/l1ax8DOkM2x0CIFOqVS4pMx7Dnfs5
          FMNsu8kcLW1PMAlcwuRHOXst5gL0
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
