---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAI+xkPLvwW1SG+xIBTm5o0YwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjExMDIyODAwWhcNMzQxMjA5MDIy
          ODAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABPthud2KDviGRmupPuDndq37ax227/ZA8K59mUm0QL9GiXlTVcfJAJoX
          jMMGfpuuV8DNd0h3aqsEXqoCDiDlf82jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgS0qWRlhetsQhETctB61JCpkJUwY4Wey/ybiM3o/XltkwCgYIKoZIzj0E
          AwIDSAAwRQIhAIEC4KfoD53V2sUMXMY3ev0ZRedyMOC1ZLMa5N+/BQmMAiAN0bpB
          WKsmrJHZoqz3OfML6Ux/J9dpmL9zvrhRgSSaKQ==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfegAwIBAgIQc6NgZs++LOuXbHqSrj8qvDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMTEwMjI4MDBaFw0zNDEyMDkwMjI4MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          OZscBuiO3g/b8+NoZ8JLVsCuinnIORZ/GQ+J+Jqh9LW2OTwVZpWqyCZEXcZg2lXW
          Rr3DhdGdujgvv0WIh3Be5KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCC/
          yfH3EL6H8OUqDI6wRh570ZYK2yb3TLdti3sOZxW1PDAKBggqhkjOPQQDAgNJADBG
          AiEA7FGzYCBR1MPKs0LctcO51+FZXDOuJ/KxW7Hc3E/LGZcCIQCzuhFiebKlG4ax
          HCx436+0+yQIKwwKDw1fS2dHlwK4EA==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
