---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRAJL6GhKu/pSyU4ThOvDkj/8wCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjE0MDkzMzAwWhcNMzQxMjEyMDkz
          MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABFaPixUmu4Nbdfedq6SqsH9YRvFZI+qTcY5S5gF30XN9sCxtFijzsJTT
          CHNdq5uiFJzY6Hk2hBDqppDuWapoL16jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQg5rXgvpXRUgJP536h7C80o35e9fC0SKvlJrQPcHxj7EAwCgYIKoZIzj0E
          AwIDRwAwRAIgLRfdxCfGZnl0laZ0M91K7QHKCN+SxFBDuRZl3IvNxiICIFGQ2B43
          /jOqAku81wIN9A0z1g2zcxnBS/cRgU4cNYA3
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRAOKXGI9x5LICVvwldRPwn0wwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjE0MDkzMzAwWhcNMzQxMjEyMDkzMzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BNmRVsCYNQGNo1p2qvRJTXWtWKL0xc/AlhYnPkkD18qsZM1yefgNdJ91tY90X4nC
          NXBhAg5xSHnaHfF44O35bQ6jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          2cfipnf1BCiFN9RWhoRO/WKJWjdvojUWD1ZOeg67M4EwCgYIKoZIzj0EAwIDSQAw
          RgIhAJVdI3f9cYHTrDlSs4WJvHE9PiN7KnILhKEMCORouFwFAiEA88yK/3uRCulv
          ggybKMfZ9FYSQKDdIaigFsXP6UwSyoA=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
