---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAPvlgyPR9M04cH8qm8DxKrswCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjA5MDcxNzAwWhcNMzQxMjA3MDcx
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABMmWuH5PfuQpB1E0DP/oHMU0SXYlhN/nBfSytNs1iaz3EFk6lB+9QDyk
          JNUN6YH7qR4S+VZAfR7mz5d/UGwHbYmjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgGjxL4Le0TOMDG85Zfp7MJGVnHz29qRjocb0oypAVtxEwCgYIKoZIzj0E
          AwIDSAAwRQIhAJNcvS8JFa6vp7UglhulmM/Oq7fGuAyfU5Ow1hLs1S72AiBmZGr0
          32Tb1O40akj7THVw0QEjjM5NtBSR1a3GoM4kEw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQMs6KyVrrBDpk9taL995NozAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMDkwNzE3MDBaFw0zNDEyMDcwNzE3MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          wUke56EnajMrqGxqIAx+hREL+g0Njy6HAYjWkQebTfOaX1h1XqlKot2eGvy9zpEZ
          J8SrGb4PW4dAT6MKG7ogj6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCo
          NGEg25/YzDumuC2Yj/O0MkRfliNhsQZiCy2kBuCgBjAKBggqhkjOPQQDAgNIADBF
          AiEAob7Ug6OBFnoqHMIiFoIvc6ldl5SlzMkkLH39dfJT2Q8CIAf5KK74L3nu6Yzt
          SU9EHkWvjQ6aFJ+/nVfwy1njnT4o
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
