---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRAPMni4x85e2zQinXiYekstcwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjEwMDI1NzAwWhcNMzQxMjA4MDI1
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABFKJqMtqKIyoqMPJ38AtpKVU9uolE9y1288DPwZ1wgFlupx9CW0W2O0k
          bgn9HIUrs0O0VesZmwKDRGMCchW1CEqjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgWQxNKIphxLljAFtD9lUKscr9FrDdSJV05XcjQuNnY18wCgYIKoZIzj0E
          AwIDSQAwRgIhAP9gmIHrlJ8uks1HS09dFqKoeSbIv5ZSRcLPGX5Snq8cAiEAnLpb
          1PvrCaDwxyOE/vgZfiZ5CKmSurAJeArdSBHbYpw=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRAPVq1044RoxiYTOmp+06mEwwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjEwMDI1NzAwWhcNMzQxMjA4MDI1NzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BLznVamiK7ImHckdJc7lc4fg4h5CcSPVall+st1WjAbbywSP+FjvQ6BD/OmyqQOZ
          EqZwUd2h2/oouCnyiHzEOlSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          u5rlseZc8iGx5DRN5s6CwQipM5zRAgsScH4suDngFKMwCgYIKoZIzj0EAwIDSAAw
          RQIgYfk1JeZx/4bgwwHJPHRImD3/yI8T0K3oRO1wSkmt8aMCIQCIgn67Yheqr46B
          ByeSRCgrwhZFeScFh9Vj2KMmGGx7gA==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
