---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf2gAwIBAgIQG+2vCiXtKcLXFFVZMN1g1TAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yNDEyMjAxMzE0MDBaFw0zNDEyMTgxMzE0
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAE9UL41GVXOpuUuyRnVnTzzkMmTWDDqQFbxv4Ab2vUEBJZUoOrrOD7sjyp
          TriMWbVmbnJ+qE0Sv+6Tza0BJM3QQaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCA03FG/GcaUdq4RfPkn1uRX2p8NI7pnhvIJc9YLZ19ebTAKBggqhkjOPQQD
          AgNJADBGAiEA9Ln647t6SAd9qExjYchYFOoh1Fq4Tsfo7r51WHigWfwCIQDiMjHv
          Aa1bpMjN0mvOhX0niuYV28VReqME3CG7JOzjIw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAPWPROBAp+BW3e3WdofvsekwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTMxNDAwWhcNMzQxMjE4MTMxNDAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BPME+LC0w5dMpwmjeOaG+SN0fzRZ2dMBFm9FNSHQigHxUD2A+Ptgm1de3U0Sm1Qd
          uJ6tQVG5qcBwSDpP6+saMZ6jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          F8S6xCJOyluDLWdpQYwb9SX/4MWiNqj31/lFFyK+NKQwCgYIKoZIzj0EAwIDRwAw
          RAIgcuuItJHUdqn6mHBWJ1UZ2V2Ibf1SnnsB3yh1pSqH2hQCICo4ZOy1vTrv6ZWH
          1T6IFELfMfn9ZD2ENtPTN8GQJv+o
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
