---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAMcUHpHbmuUdgLnN9aLUPvcwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTAzNDAwWhcNMzQxMjE4MTAz
          NDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABPujHgYSTVGx76RXX308/hSmHZR9s/9AmkxTAHfgwbRV2ziV0BOHxG62
          3jYVVSDCJfsBKK17pDczrA1Q9qT6cI+jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgGKYRKeEbqdE+JityCRNerLdgAn61tTDEXrngbGGKo4YwCgYIKoZIzj0E
          AwIDSAAwRQIhAJyNgHa6FPaeg2r09xfJ7YP9LrnjmP9X3pL+PJQUbhBlAiBUXuKu
          poS83NcSX4aeK7CqNwrbhFJfIaFnthLQy6hvqQ==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRALLKCwjlBS+umMtS7Ow48GgwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjIwMTAzNDAwWhcNMzQxMjE4MTAzNDAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BON1bpZMRe8uQb9x/Y0WABes6q+41ORfraupkMXZaM1vLZim78RwJT0UDBz75WOg
          TdId8u+wFVEl0IzXEvpGu9qjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          GdcV59ccew54p+W3BAsudtKRG637Sk3yXRDjKAIPRAEwCgYIKoZIzj0EAwIDSAAw
          RQIgez+8NPcUZNwegDVdmvJPTVes+tPuVyvYFtR3Vl2iS5QCIQCpwPkIgjB6m/0e
          i7tUSGbpic0d1+WYF3qikdi1cMKvrw==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
