---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAPMG/0hZOMeMxXENQdmdbzcwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjA1MTY0MjAwWhcNMzQxMjAzMTY0
          MjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABC+hzWkvAW5oWSxj+21YufKZqdo3tEKlN8BtOBpAIw4wVSKQh7dgjPaC
          waeudkbc/ebqLxhm2PwIRxWJnbrZ/qujbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQg2evCShHVKkDCVvxyfvG+KmkHR/LfuAtZA2s1zXunZjkwCgYIKoZIzj0E
          AwIDSAAwRQIhAMYexh156FC+eaMi/Es0hmxd/BAHDcTZjn+jWs7skWLoAiBrtiS3
          CMzMsdz969bxkEpOOcZDeWg2ovTRMIxQD9paUA==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRANvSl0Mb00dJ3//F1LlnSYIwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMjA1MTY0MjAwWhcNMzQxMjAzMTY0MjAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BJvq897XRQOkn1/suG45lbz7mnhzVROcjo/N58DTNGSxSQyF4KN56qoAKe5XIlDu
          1N7j0Ui2NXbmu4uU/bLEOCOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          aWML1gQGgy+D+Z9bsHYKTgPXaos7MeBldFAQQTgBBMMwCgYIKoZIzj0EAwIDSQAw
          RgIhANlrCEKchhnZnNovLUyIEnnsgvGEuWCV+8+tEofFxxupAiEAgc5Xh/UiXnOk
          /PJAG+c8Y7aZEGlYQTNcDWWygJfUP0A=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
