---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVjCCAf2gAwIBAgIQbrE8O9BOYSa9KNUxiLt9WTAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMTAxMTA3MDBaFw0zNDEyMDgxMTA3
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAE/0K9sympAB2H64IH+B8ybbtez7yAZkf8ENZB10UhRtx65e+Y+KpEHyaF
          oy/dbnDOBNJewZUA7i+GmJszEw2rF6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCCnf04JHGUvLGySjdKLLnrp+bHZSybpTI5P3h3Gp0iM1DAKBggqhkjOPQQD
          AgNHADBEAiBOZXwaHTfGPaYQ+yiqqpMyJ17HLaHa7uZ27kaAO99TSQIgFVagOAGB
          xSsiY+k2DlooKTjuS6kcGz1xj9Fejk2SEAw=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQPgiW1LCq2IBUQwHjwFEF9TAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMTAxMTA3MDBaFw0zNDEyMDgxMTA3MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          em9yZqCVMasOttqUc8HpquMydqidbObyPYn1jx1SIIxjxZBUsmUnYI62rNWX+Ygy
          XkQFKLIid8wkq1fxx2SGraNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCq
          eks6hLweIX0yqvDTxWdZ0IErzxnnRMDcFrmQgth48TAKBggqhkjOPQQDAgNIADBF
          AiEAnGcKfAWr6orgw753b+lptnQIkFyFhmKKWf63z49iO3kCIHSN6sHpot59kxaw
          A5MOTWwpOdNaFlK7QEW5Zvv4p5XC
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
