---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAOqTWemo++VhChaLwuqU6CIwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjAyMDM1ODAwWhcNMzQxMTMwMDM1
          ODAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABN/SQWI7yq+slj+Gi6n/al+0Xi4HDL7OaN2Veiwp1jz22G9EfQhdtAMy
          mKON8WtFQ5XuCjeyfzgPxcNiznlFmb+jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgluj0R3hAUpW9gw26XtiupUAVMV/PW07cs+nfClD9+yowCgYIKoZIzj0E
          AwIDSAAwRQIgdGs+9VWInhtpEJ0OsM4wWCdOGUEduQpqke39E1jPzXACIQDMvK6o
          UQNMKUa/TlYmNSZjaehItbxIuGzR/GKGd4allQ==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRAIMXfJAqLhUvNRdBIAu6cbIwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjAyMDM1ODAwWhcNMzQxMTMwMDM1ODAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BGtkmLwxvBQbuujP/gPrUpFdMBqX+5I4gV085iOSSeX4TwdJ9B6tGeD02UJw0XW3
          KoqJ0s5dl8Cgm7KofirkjwmjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          iz/XH2sdEpcIU7Q8i68ksh+zUA3R1JFU5OukWJH3kFQwCgYIKoZIzj0EAwIDSQAw
          RgIhAORAqPjewDjTXnYlHPYQedQRi0Lz478xtBtGe6h6gXy5AiEAuNf/nre3lGFR
          Ec1VbFQraQfElTkflx6rG4ZgdGixp24=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
