---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWTCCAf6gAwIBAgIRAOH/7CnO5yUnP7ZoZv+tyyEwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjE0MDkzMzAwWhcNMzQxMjEyMDkz
          MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABJBx8gu22S0ZQc1HXemd9H10Bp7UAMjGetpceJdU5kPnTps/PrrhyK5h
          sI04kA3aaCMNlIdIPbzmhyxeOUdhm02jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgX+z88QCG8IjXCQVGPfZ2k6L1lDrtyN9rhnyoWoAlzXQwCgYIKoZIzj0E
          AwIDSQAwRgIhAIML4LRqMuYpV0V+ae2SC9jD1P42hfdkxB8G0TAyPX/IAiEAkcqr
          XHiuaL5EayolpE8WRMWZlCCtQO0XrwKYUfKG1cM=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAOiVIBxzTH+wMtHjrzirw2gwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjE0MDkzMzAwWhcNMzQxMjEyMDkzMzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BB+jadIWLebp9ZcIqvzDXw+JpOm1Z3xtngPIhD0Kl+Y3d68BrlFAVehPW1mKrdYQ
          fUspv9F+XvQaCJ0LFXU1Yd2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          I1oZiNpzpl2VEqT9yoUVZqvKNaTswpHE7klsjhcHR/cwCgYIKoZIzj0EAwIDRwAw
          RAIgKYkmjk/KL8Xdg4hi9TSOf742w3hBD0gIecq4lV3RD90CIBHhboeVD8l6riJ7
          wlK1yK/Fxg9+FdD+15nDqN2WbLNU
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
