---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVjCCAf2gAwIBAgIQBW2uCICEg37CXidrynXMgDAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMTEwMjI4MDBaFw0zNDEyMDkwMjI4
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAESMqZKNL5bJeQuHEammORKEzFjHfzYfecErd5hXyeSQCq7DVnQq1qJz2r
          F8aX1XwrGEiPRjicN/M+Pn678NOmWKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCDC9raEz2ADp6YHh+F7V5UmmLmoYvorJARPdU0PQ3q4yTAKBggqhkjOPQQD
          AgNHADBEAiBpyluMEXwAbvbPlyZrhsRwudLCB2IlMwRbczMSwF+BqwIgHGuNLHJk
          ioVFy2zns9ZEgPYuzI6OyODjA+MTI9U4WAI=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUzCCAfigAwIBAgIRAKQ2WlHuT0swuX1rYbuWmV4wCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjExMDIyODAwWhcNMzQxMjA5MDIyODAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BOtu3mB7Fw8xtf0xCb9PzcT2Ll2N4fkkT0f5PjBr7+iVQ8IDGwNgqBpIfdlgVpZi
          exL145ZDOudB2Rmm0yP8e/OjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          GvEJMcdmfSWspurIS+c0giqoRnT/QtiXP6D4LTJ46fMwCgYIKoZIzj0EAwIDSQAw
          RgIhAM+PgbrqdA/Oa/gDIWDvL7GT8zew6w959eOEQTcyF+w2AiEA5sJQd8ddhVGG
          MtcV6wJvemA0lRN4tFOZzIGsk28u7/8=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
