---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVjCCAf2gAwIBAgIQG2SsualTfhzoHBFEMTyFYzAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMDIxMjM2MDBaFw0zNDExMzAxMjM2
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEFPe9Hu7Em1a6vuMktHzrOiQJDaQtnOkFMNW0zEbPp56hSza0ElCf0xHx
          YAvRUASq61yUlCKv/dDUoi8cUhmnX6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCA5WQ+N9lkEgOhL6fVVN3hCBJqkwY9G7nfO76LVUS+ACDAKBggqhkjOPQQD
          AgNHADBEAiAvBE/Wd5D+jjVUmrdjOjig2S7DQHLNuO15VGIW5vGSUgIgeKj+41LP
          WOjrRgU5FsgCuzsrckqy/i2WCl9Q11hqmQE=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAMJSPhlvB25YtF0f0huSSrQwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjAyMTIzNjAwWhcNMzQxMTMwMTIzNjAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BFQpfYGtymBdfhUlUZoxFXaYyrNuzPYwk0G1GsNpjNEjMbh50N/gHhfa8LGzjrY1
          gQF+dlbu+qhNtIcsVb8tlV6jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          CcP5qrdAt+ayFwhhZMhQvbABvNew9pfc2qPZAQA0XMYwCgYIKoZIzj0EAwIDRwAw
          RAIgcQ32QqgvUqKHZ3SNrdv3bq8LL867QlDHqWeBwReB1bICIEQWNk6w22TZPpSy
          +WXaJG/c0+uW+FdsBtZfzDc8ZElC
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
