---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAP+/5hP16DQi7O9pTmLkrdIwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMTIyMDkyNTAwWhcNMzQxMTIwMDky
          NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABMVAALaL3yjrDg+yrZHv4NW2G2L2cxsCFKVXqg2BBwmyubq/YoyJYDqG
          /J5D/Bxriv3nvc2qLl4waGpQjurDvNujbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgtFE8qZqggw4tlGuxrznPCfnxXtMmdCbmukFyARDdIPowCgYIKoZIzj0E
          AwIDSAAwRQIhAMHXDzYUMRt1TWnLtMzvMkXNf2eCE0crk6zKqbX5MmfWAiAmxc5+
          JtulLkACSGB0TeRZxzEpE8yQbooEF/DTrKstAw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAOaQDOJ9Sd9I14SDK/KbyUYwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMTIyMDkyNTAwWhcNMzQxMTIwMDkyNTAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BEsAVNz8oeLvBjYB1ZaH6zHF7Bz3p2kVHK2kfJ0196SynQuCzT+5NelUouwAt3rK
          mrwaWVdpDoUc7Ds1x9CA526jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          m1hURyf930ND0L41wzQBxHH43dc2Qx/tgksqlQrFGfEwCgYIKoZIzj0EAwIDRwAw
          RAIgUsiU91FY1T9juzjSTs3pi8avnG7xXM0JKCLsKSKSYQ4CIC2XqScXesJj/NRo
          A6rxc4809ZcbtdQ2aLbWlwcJAAJS
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
