---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVjCCAf2gAwIBAgIQGbgTX8Ol8Mo7zzlw4oFH5jAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDEyMDYwNDQ5MDBaFw0zNDEyMDQwNDQ5
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAERE7Vu0VPDDGtCXLYDtkvtyW833m9s966/oshIptjgMzvdsq5mFMotYmx
          L4FanwPDgq1+7Z90MkFKKCd5ErYHD6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCDrDxx1DK45SerZBa+cMj2qEMVPSx0vRL9QaGDE0OU0QzAKBggqhkjOPQQD
          AgNHADBEAiAs/9byDfz63ZU+QHYHFNZXNaeZriJKvpWDN87a+ua5DgIgQeYj7G55
          t4i1HeM4hLDYnWLMDKs7fycjVfylu9wFP60=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRAKESZhVDVeYf+GvDdqBsJfUwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQxMjA2MDQ0OTAwWhcNMzQxMjA0MDQ0OTAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BIqlrUG3Zt0GvwvLpvMtd/3Uonmh04ZBtfwV656C6Uti+DH04EOp1hg+GP2YwRYm
          0TH4rcedVNZUffKJyi9cvnOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          EQ4eyrQoXj5t1dEMuLaDFzScysr6nJF5q0DQvEctmWgwCgYIKoZIzj0EAwIDSAAw
          RQIgOYow730BgyaNpVC06z95JKvHDwB4MD8BN1W98q77p38CIQDv+F8RGCkBaKen
          PrzD/zPKVM66oYm/LEuqv78uhHCfwA==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
